name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t francdocmain/fastapi-app:latest .
          docker tag francdocmain/fastapi-app:latest francdocmain/fastapi-app:$(git rev-parse --short HEAD)
          docker push francdocmain/fastapi-app:latest
          docker push francdocmain/fastapi-app:$(git rev-parse --short HEAD)

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Docker Setup Script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "scripts/ec2-setup.sh"
          target: "/home/ubuntu/ec2-setup.sh"

      - name: Run Docker Setup Script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/ubuntu/ec2-setup.sh
            sudo /home/ubuntu/ec2-setup.sh

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull francdocmain/fastapi-app:latest

            echo "Deploying with zero-downtime..."
            docker stop fastapi-app-2 2>/dev/null || true
            docker run -d -p 8001:8000 --name fastapi-app-2 francdocmain/fastapi-app:latest

            sleep 10

            echo "Switching traffic to new container..."
            docker stop fastapi-app-1 2>/dev/null || true
            docker rm fastapi-app-1 2>/dev/null || true
            docker rename fastapi-app-2 fastapi-app-1

            echo "Deployment complete. Current running containers:"
            docker ps -a